application: weishiapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /www
  static_dir: www
  
- url: /.*
  script: locate.application 

libraries:
- name: webapp2
  version: latest
